// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyTIML-LA5lDP155reV8fLB6mC1fQDL88',
    appId: '1:1061982765527:web:1d6b52d589e5b2c0f3cb92',
    messagingSenderId: '1061982765527',
    projectId: 'fitsy-5wx21',
    authDomain: 'fitsy-5wx21.firebaseapp.com',
    storageBucket: 'fitsy-5wx21.appspot.com',
    measurementId: 'G-VGWY9R28CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5KBgTgoE-ETb78Er88rHJ6HC7i4sOa0s',
    appId: '1:1061982765527:android:181e1397a79c13b9f3cb92',
    messagingSenderId: '1061982765527',
    projectId: 'fitsy-5wx21',
    storageBucket: 'fitsy-5wx21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd7-J-NBcKRWt7PPqg5h3-xgO9V2F5x14',
    appId: '1:1061982765527:ios:c9412b90c39326c2f3cb92',
    messagingSenderId: '1061982765527',
    projectId: 'fitsy-5wx21',
    storageBucket: 'fitsy-5wx21.appspot.com',
    iosClientId: '1061982765527-9vt42atmr2mfhag69i808sf66nd16q5i.apps.googleusercontent.com',
    iosBundleId: 'ca.fitsy.testing',
  );
}
